version: 2

jobs:
  build:
    docker:
      - image: docker:17.03.0-ce
    working_directory: /Alms
    steps:
      - setup_remote_docker
      - run:
          name: Show Info
          command: |
            docker version
            docker info
      - checkout
      - run:
          name: Build the current image
          command: |
            TAG=build
            docker build -f Dockerfile -t ritsse/alms:$TAG .
      - run:
          name: Distribute
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                TAG=2.0.${CIRCLE_BUILD_NUM}
                docker tag ritsse/alms:build ritsse/alms:latest
                docker tag ritsse/alms:build ritsse/alms:2.0
                docker tag ritsse/alms:build ritsse/alms:$TAG
                docker push ritsse/alms:$TAG
                docker push ritsse/alms:2.0
                docker push ritsse/alms:latest
            fi
